name: Publish Homey App
on:
  workflow_dispatch:

jobs:
  main:
    name: Publish Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Create env file'
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "env.json"
          json: '{ "TEST" = "1" }'
          
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --ignore-scripts --audit=false

      - name: App needs to pass verified level validation
        run: HOMEY_HEADLESS="1" HOMEY_PAT="${{ secrets.HOMEY_PAT }}" npx homey app publish